default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: book_my_movie_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: book_my_movie_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: book_my_movie_production
  username: postgres
  password: postgres
